### PR TITLE
143 fix virtual serialization with abstract classes in hierarchy

### LINKED ISSUE #143: virtual serialization: "Error, could not find corresponding entry in derived for base" when serializing non constructible classes
_Scenario based on serialization of `vt::objgroup::holder::HolderBase` (required for `vt::objgroup::ObjGroupManager` component)._

Given following class hierarchy:
```cpp
struct HolderBase {
  checkpoint_virtual_serialize_root()

  virtual ~HolderBase() = default;

  template <typename Serializer>
  void serialize(Serializer& s) {}
};

template <typename ObjT>
struct HolderObjBase : HolderBase {
  checkpoint_virtual_serialize_derived_from(HolderBase)

  virtual ObjT* get() = 0;

  template <typename Serializer>
  void serialize(Serializer& s) {}
};

template <typename ObjT>
struct HolderBasic final : HolderObjBase<ObjT> {
  checkpoint_virtual_serialize_derived_from(HolderObjBase<ObjT>)

  ObjT* get() override { return obj_; }
  ObjT* obj_ = nullptr;

  template <typename Serializer>
  void serialize(Serializer& s) {}
};
```

When virtual serialization is attempted: 	
```cpp
  std::unique_ptr<HolderBase> ptr = std::make_unique<HolderBasic<int>>();
  checkpoint::getMemoryFootprint(ptr);
```

Test crashes with following error:
```
-----------------------------------------------------------------------
Assertion failed in Checkpoint library:
-----------------------------------------------------------------------
   Reason: Error, could not find corresponding entry in derived for base
Condition: false
     File: ../src/checkpoint/dispatch/vrt/serializer_registry.h
     Line: 156
     Func: getBaseIdx
-----------------------------------------------------------------------
```

Backtrace after crash:
```
(...)
#4  in checkpoint::debug::assertOut (cond=0x5555555f6de6 "false", str=0x5555555f6da8 "Error, could not find corresponding entry in derived for base", 
    file=0x5555555f6a90 "../src/checkpoint/dispatch/vrt/serializer_registry.h", line=156, func=0x5555555f6d97 "getBaseIdx") at ../src/checkpoint/common.h:103
#5  in checkpoint::dispatch::vrt::serializer_registry::getBaseIdx<checkpoint::tests::unit::HolderObjBase<int> > (base_idx=0)
    at ../src/checkpoint/dispatch/vrt/serializer_registry.h:156
#6  in checkpoint::tests::unit::HolderObjBase<int>::_checkpointDynamicSerialize (this=0x5555556634a0, s=0x7fffffffd7b0, base_ser_idx=0, expected_idx=1)
    at ../tests/unit/test_footprinter.cc:543
#7  in checkpoint::tests::unit::HolderBasic<int>::_checkpointDynamicSerialize (this=0x5555556634a0, s=0x7fffffffd7b0, base_ser_idx=0, expected_idx=-1)
    at ../tests/unit/test_footprinter.cc:553
#8  in checkpoint::dispatch::vrt::virtualSerialize<checkpoint::tests::unit::HolderBase, checkpoint::Footprinter> (base=@0x7fffffffd4c8: 0x5555556634a0, s=...)
    at ../src/checkpoint/dispatch/vrt/virtual_serialize.h:66
(...)
```

### PR DESCRIPTION
**Pull request by cz4rs**
Fixes #143

### CODE REVIEW

**Comment by lifflander** [comment]
I just pushed the fix. I used too strong a trait when I refactored for #127 for specialized serializers.

This was stopping registration of classes that are not concrete because they aren't constructible by definition.

**Review by PhilMiller — APPROVED** [review]
This fixes the failure I was encountering in EMPIRE

**Review by PhilMiller — APPROVED** [review]

**Comment by cz4rs** [comment]
I've just confirmed that this fixes the issue that I was facing in `vt` as well :+1:

**Comment by PhilMiller** [comment]
Modified/moved test code is broken due to missing constructors entirely

**Comment by lifflander** [comment]
> Modified/moved test code is broken due to missing constructors entirely

Yes, I just fixed it. Copy-paste error

**Pull request merged**
