### PR TITLE
#296: Specify no-c++-extensions so that compiler command-line flags to nvcc avoid warnings

### LINKED ISSUE #296: nvcc CI builds warn about `-std=gnu++17` for every file
E.g.
https://github.com/DARMA-tasking/magistrate/actions/runs/4547537292/jobs/8017542900#step:7:164

```
[1/142] Building CXX object src/CMakeFiles/checkpoint.dir/checkpoint/serializers/sizer.cc.o
nvcc_wrapper has been given GNU extension standard flag -std=gnu++17 - reverting flag to -std=c++17
[2/142] Building CXX object src/CMakeFiles/checkpoint.dir/checkpoint/buffer/io_buffer.cc.o
nvcc_wrapper has been given GNU extension standard flag -std=gnu++17 - reverting flag to -std=c++17
[3/142] Linking CXX static library src/libcheckpoint.a
[4/142] Building CXX object examples/CMakeFiles/checkpoint_example_traversal_nonintrusive.dir/checkpoint_example_traversal_nonintrusive.cc.o
nvcc_wrapper has been given GNU extension standard flag -std=gnu++17 - reverting flag to -std=c++17
[5/142] Linking CXX executable examples/checkpoint_example_traversal_nonintrusive
[6/142] Building CXX object examples/CMakeFiles/checkpoint_example_traversal.dir/checkpoint_example_traversal.cc.o
nvcc_wrapper has been given GNU extension standard flag -std=gnu++17 - reverting flag to -std=c++17
[7/142] Linking CXX executable examples/checkpoint_example_traversal
[8/142] Building CXX object examples/CMakeFiles/checkpoint_example_to_file_nonintrusive.dir/checkpoint_example_to_file_nonintrusive.cc.o
nvcc_wrapper has been given GNU extension standard flag -std=gnu++17 - reverting flag to -std=c++17
[9/142] Linking CXX executable examples/checkpoint_example_to_file_nonintrusive
[10/142] Building CXX object examples/CMakeFiles/checkpoint_example_to_file.dir/checkpoint_example_to_file.cc.o
nvcc_wrapper has been given GNU extension standard flag -std=gnu++17 - reverting flag to -std=c++17
[11/142] Linking CXX executable examples/checkpoint_example_to_file
[12/142] Building CXX object examples/CMakeFiles/checkpoint_example_2_nonintrusive.dir/checkpoint_example_2_nonintrusive.cc.o
nvcc_wrapper has been given GNU extension standard flag -std=gnu++17 - reverting flag to -std=c++17
```

### LINKED ISSUE #2126: Set `-DCMAKE_CXX_EXTENSIONS=OFF` on Magistrate CI installation so that nvcc doesn't get incorrect  `-std=gnu++17`
Right now, nvcc builds warn about the files compiled within Magistrate

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #296

### CODE REVIEW

**Comment by PhilMiller** [comment]
This (Edit: `CMAKE_CXX_STANDARD=17`) doesn't suffice

**Comment by PhilMiller** [comment]
may need `CMAKE_CXX_EXTENSIONS=OFF`

**Comment by PhilMiller** [comment]
That seems to do it.

**Comment by PhilMiller** [comment]
Hrm, maybe I should go straight to `target_properties` for this?

**Review by lifflander — APPROVED** [review]

**Pull request merged**
