### PR TITLE
#254: Clean up reconstruction logic for View, DynRankView, and DynamicView

### LINKED ISSUE #254: Simplify View/DynRankView reconstruction after Kokkos 3.7 ships
Kokkos 3.7 will include changes to properly round-trip the layout associated with a View(https://github.com/kokkos/kokkos/pull/5188), and DRV will likely do the same https://github.com/kokkos/kokkos/pull/5026 Thus, we can simplify the logic in `constructRankedView` and its callees down the stack.

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #254

### CODE REVIEW

**Comment by PhilMiller** [comment]
This depends on at least Kokkos 3.7. I don't want to charge ahead with merging yet without at least a little bit of thought about the test that I had to disable because of https://github.com/kokkos/kokkos/issues/5609

It may be worth just going ahead, and we can run the concrete sibling test on real CUDA systems. It was mostly there as a TDD thing.

**Comment by PhilMiller** [comment]
On further consideration, I think we can leave that test disabled for now, and maybe turn it back on if/when Kokkos loosens up or otherwise improves usability of logical memory spaces.

**Review by cz4rs — APPROVED** [review]
Looks good to me!

**Comment by cz4rs** [comment]
> On further consideration, I think we can leave that test disabled for now, and maybe turn it back on if/when Kokkos loosens up or otherwise improves usability of logical memory spaces.

Should we create a follow-up issue or maybe include a reference to https://github.com/kokkos/kokkos/issues/5609 in the disabled test?

**Comment by PhilMiller** [comment]
Follow-up issue created. Merging.

**Pull request merged**
