### PR TITLE
136: test: fix compilation warnings in unit tests

### LINKED ISSUE #136: fix compilation warnings in unit tests (variadic macro parameters)
Fix all the warnings concerning the use of `INSTANTIATE_TYPED_TEST_CASE_P` macro in tests:
```
/usr/src/checkpoint/tests/unit/test_container.cc:139:77: warning: must specify at least one argument for '...' parameter of variadic macro [-Wgnu-zero-variadic-macro-arguments]
INSTANTIATE_TYPED_TEST_CASE_P(Test_int, TestContainer, ContOrderedTypes<int>);
                                                                            ^
/usr/include/gtest/gtest-typed-test.h:290:10: note: macro 'INSTANTIATE_TYPED_TEST_CASE_P' defined here
# define INSTANTIATE_TYPED_TEST_CASE_P(Prefix, CaseName, Types, ...)      \
         ^
```

See `vt` issue for reference: https://github.com/DARMA-tasking/vt/issues/512

### PR DESCRIPTION
**Pull request by cz4rs**
Fixes #136

### CODE REVIEW

**Review by lifflander — APPROVED** [review]
Looks good

**Comment by cz4rs** [comment]
> Looks good

Thanks, that was quick!

**Comment by cz4rs** [comment]
@lifflander @PhilMiller 
It seems that there are 3 last warnings left in kokkos-enabled build (comparison between signed and unsigned integer). After fixing those we could add `-Werror` in `turn_on_warnings.cmake`. Any objections to that?

**Comment by PhilMiller** [comment]
We can make an option to add `-Werror`, but we can't do it unconditionally. The range of compilers we deal with, and the continual addition of new ones, and the fact that this is a library that we don't want harming users' development, all mean we can't add it unconditionally.

**Pull request merged**
