### PR TITLE
#272: Add unit test to cover empty base optimization when using tuple

### LINKED ISSUE #272: Unit test for `std::tuple` serialization
There can be a pitfall with `std::tuple` where the offset of each element is implementation defined rather than a contiguous buffer. For example, an empty struct tuple element might have a size of 0 instead of a size of 1 due to empty base class optimization. We should unit test this proactively in order to avoid issues before they come up

### PR DESCRIPTION
**Pull request by thearusable**
Closes #272

### CODE REVIEW

**Review by nmm0 — COMMENTED** [review]
Thanks for doing this. Any chance you could add a test with Base?

The reason I'm asking as that at least in gcc, tuple uses inheritance and therefore EBO:

https://godbolt.org/z/G1qjsEGcx

i.e. `sizeof(std::tuple<empty, int>) == 4` but `sizeof(empty)+sizeof(int) == 5`. So the serialized size might not be the size of the tuple

**Comment by thearusable** [comment]
> Thanks for doing this. Any chance you could add a test with Base?
> 
> The reason I'm asking as that at least in gcc, tuple uses inheritance and therefore EBO:
> 
> https://godbolt.org/z/G1qjsEGcx
> 
> i.e. `sizeof(std::tuple<empty, int>) == 4` but `sizeof(empty)+sizeof(int) == 5`. So the serialized size might not be the size of the tuple

@nmm0 Sure I'll add this

**Comment by thearusable** [comment]
@nmm0 I extended the tuple tests. I added checks for serialized buffer sizes and a test with Base type. 
Is that what you had in mind?

**Review by nmm0 — APPROVED** [review]
Looks good! Thanks for doing this

**Pull request merged**
