### PR TITLE
71 vector of bool serialization

### PR DESCRIPTION
**Pull request by mperrinel**
Add a specialization of the serialization template method to handle vector of bool with its test.

### CODE REVIEW

**Review by lifflander — APPROVED** [review]
Looks good.

**Comment by mperrinel** [comment]
@lifflander if you can click on the merge button because I don't have the authorization :

> The base branch restricts merging to authorized users

**Comment by lifflander** [comment]
@mperrinel  I just merged it. It's supposed to allow merging if approval is given.

**Comment by lifflander** [comment]
@mperrinel Permissions for merging should be fixed now.

**Pull request merged**
