### PR TITLE
fix kokkos view serializaiton for UVM=OFF case

### PR DESCRIPTION
**Pull request by rppawlo**
Changes to fix the kokkos view serialization for when UVM is disabled. The views need to be mirrored on host and deep_copied to/from device.

Just started the UVM removal in empire. There may be more changes required, but this is what I have so far...

@PhilMiller @lifflander @nlslatt

### CODE REVIEW

**Comment by PhilMiller** [comment]
Could you compare/contrast this with #202? I can try to get that integrated this week if the issue is now becoming timely

**Comment by rppawlo** [comment]
You have the exact same changes as my PR (plus a few more in another section of the file). So if you merge that we are all set.

**Comment by PhilMiller** [comment]
#202 is set. Please accept the invitation to the DARMA org, and I'll add you as a reviewer.

Note that we'll want to get the Kokkos 3.6 release from Trilinos, and then add a hotpatch of [Kokkos#4805](https://github.com/kokkos/kokkos/pull/4805)

**Comment by rppawlo** [comment]
@PhilMiller - did https://github.com/kokkos/kokkos/pull/4805 not make it into the kokkos 3.6 release?

**Comment by PhilMiller** [comment]
No, it was posted after the branch was made.

**Pull request closed without merging**
